apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: xvancoa-gitops-repo # v spoločnom klastri je nasadených viacero takýchto objektov
  namespace: wac-hospital
spec:
  interval: 1m0s
  ref:
    branch: main
  timeout: 1m0s
  url: https://github.com/AdrianVanco/ambulance-gitops2

# ak používate privátny repozitár nezabudnite doplniť autentifikačné údaje
# secretRef:
#    name: xvancoa-repository-pat